spring.application.name=dashboard

spring.datasource.url=jdbc:postgresql://localhost:5432/dashboard
spring.datasource.username=dev
spring.datasource.password=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true